// Code generated by scripts/generate.sh. DO NOT EDIT.

package v202505

import (
	admanager "google-admanager-api-go"
	"github.com/hooklift/gowsdl/soap"
)

// Version is the Ad Manager API version this package targets.
const Version = "v202505"

// NewService returns a *soap.Client configured for the given service name
// (e.g. "NetworkService") under API version v202505.
func NewService(c *admanager.Client, serviceName string) *soap.Client {
	return admanager.NewServiceClient(c, Version, serviceName)
}
