// Code generated by scripts/generate.sh. DO NOT EDIT.

package v202602

import (
	admanager "google-admanager-api-go"
	"github.com/hooklift/gowsdl/soap"

	"google-admanager-api-go/services/v202602/network_service"
	"google-admanager-api-go/services/v202602/order_service"
	"google-admanager-api-go/services/v202602/line_item_service"
	"google-admanager-api-go/services/v202602/company_service"
	"google-admanager-api-go/services/v202602/creative_service"
	"google-admanager-api-go/services/v202602/creative_set_service"
	"google-admanager-api-go/services/v202602/inventory_service"
	"google-admanager-api-go/services/v202602/report_service"
	"google-admanager-api-go/services/v202602/user_service"
	"google-admanager-api-go/services/v202602/forecast_service"
	"google-admanager-api-go/services/v202602/custom_targeting_service"
	"google-admanager-api-go/services/v202602/line_item_creative_association_service"
	"google-admanager-api-go/services/v202602/placement_service"
	"google-admanager-api-go/services/v202602/publisher_query_language_service"
)

// Version is the Ad Manager API version this package targets.
const Version = "v202602"

// NewService returns a *soap.Client configured for the given service name
// (e.g. "NetworkService") under API version v202602.
func NewService(c *admanager.Client, serviceName string) *soap.Client {
	return admanager.NewServiceClient(c, Version, serviceName)
}

// NewNetworkService creates a NetworkService client for API version v202602.
func NewNetworkService(c *admanager.Client) network_service.NetworkServiceInterface {
	return network_service.NewNetworkServiceInterface(NewService(c, "NetworkService"))
}

// NewOrderService creates a OrderService client for API version v202602.
func NewOrderService(c *admanager.Client) order_service.OrderServiceInterface {
	return order_service.NewOrderServiceInterface(NewService(c, "OrderService"))
}

// NewLineItemService creates a LineItemService client for API version v202602.
func NewLineItemService(c *admanager.Client) line_item_service.LineItemServiceInterface {
	return line_item_service.NewLineItemServiceInterface(NewService(c, "LineItemService"))
}

// NewCompanyService creates a CompanyService client for API version v202602.
func NewCompanyService(c *admanager.Client) company_service.CompanyServiceInterface {
	return company_service.NewCompanyServiceInterface(NewService(c, "CompanyService"))
}

// NewCreativeService creates a CreativeService client for API version v202602.
func NewCreativeService(c *admanager.Client) creative_service.CreativeServiceInterface {
	return creative_service.NewCreativeServiceInterface(NewService(c, "CreativeService"))
}

// NewCreativeSetService creates a CreativeSetService client for API version v202602.
func NewCreativeSetService(c *admanager.Client) creative_set_service.CreativeSetServiceInterface {
	return creative_set_service.NewCreativeSetServiceInterface(NewService(c, "CreativeSetService"))
}

// NewInventoryService creates a InventoryService client for API version v202602.
func NewInventoryService(c *admanager.Client) inventory_service.InventoryServiceInterface {
	return inventory_service.NewInventoryServiceInterface(NewService(c, "InventoryService"))
}

// NewReportService creates a ReportService client for API version v202602.
func NewReportService(c *admanager.Client) report_service.ReportServiceInterface {
	return report_service.NewReportServiceInterface(NewService(c, "ReportService"))
}

// NewUserService creates a UserService client for API version v202602.
func NewUserService(c *admanager.Client) user_service.UserServiceInterface {
	return user_service.NewUserServiceInterface(NewService(c, "UserService"))
}

// NewForecastService creates a ForecastService client for API version v202602.
func NewForecastService(c *admanager.Client) forecast_service.ForecastServiceInterface {
	return forecast_service.NewForecastServiceInterface(NewService(c, "ForecastService"))
}

// NewCustomTargetingService creates a CustomTargetingService client for API version v202602.
func NewCustomTargetingService(c *admanager.Client) custom_targeting_service.CustomTargetingServiceInterface {
	return custom_targeting_service.NewCustomTargetingServiceInterface(NewService(c, "CustomTargetingService"))
}

// NewLineItemCreativeAssociationService creates a LineItemCreativeAssociationService client for API version v202602.
func NewLineItemCreativeAssociationService(c *admanager.Client) line_item_creative_association_service.LineItemCreativeAssociationServiceInterface {
	return line_item_creative_association_service.NewLineItemCreativeAssociationServiceInterface(NewService(c, "LineItemCreativeAssociationService"))
}

// NewPlacementService creates a PlacementService client for API version v202602.
func NewPlacementService(c *admanager.Client) placement_service.PlacementServiceInterface {
	return placement_service.NewPlacementServiceInterface(NewService(c, "PlacementService"))
}

// NewPublisherQueryLanguageService creates a PublisherQueryLanguageService client for API version v202602.
func NewPublisherQueryLanguageService(c *admanager.Client) publisher_query_language_service.PublisherQueryLanguageServiceInterface {
	return publisher_query_language_service.NewPublisherQueryLanguageServiceInterface(NewService(c, "PublisherQueryLanguageService"))
}

